// This file was autogenerated by calcdeps.py
goog.addDependency("base.js", [], []);
goog.addDependency("entity.js", ['sprintly.Entity'], []);
goog.addDependency("loader.js", ['sprintly'], ['sprintly.Product', 'sprintly.Service']);
goog.addDependency("product.js", ['sprintly.Product'], ['sprintly.Entity', 'sprintly.Service']);
goog.addDependency("service.js", ['sprintly.Service'], []);
